config/routes.rb
Rails.application.routes.draw do
  
  match 'answers/record' => 'answers#record', via: [:get, :post]
  match 'pages/word_cloud/:id' => 'pages#word_cloud', via: [:get]
  match 'pages/bar_chart/:id' => 'pages#bar_chart', via: [:get]
  match 'pages/geo_results/:id' => 'pages#geo_results', via: [:get]
  match 'pages/says_who/:id' => 'pages#says_who', via: [:get]
  match 'prompts/set_active/:id' => 'prompts#set_active', via: [:get, :post]
  
  resources :answers
  resources :choices
  resources :prompts, :has_many => :choices
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
  
end

app/models/prompt.rb
class Prompt < ActiveRecord::Base

  belongs_to :user
  has_many :choices
  has_many :answers
  accepts_nested_attributes_for :choices, allow_destroy: true

end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
  before_action :set_prompt, only: [:show, :edit, :update, :destroy]
  
  layout "admin"

  # GET /prompts
  # GET /prompts.json
  def index
    @prompts = Prompt.order('created_at ASC').all
  end

  # GET /prompts/1
  # GET /prompts/1.json
  def show
  end

  # GET /prompts/new
  def new
    @prompt = Prompt.new
  end

  # GET /prompts/1/edit
  def edit
  end

  def set_active
    current_active_prompts = Prompt.where(active: true).all
    new_active_prompt = Prompt.find(params[:id])
    
    current_active_prompts.each do |prompt|
      prompt.active = false
      prompt.save
    end
 
    new_active_prompt.active = true
    new_active_prompt.save
  
    render nothing: true
  
  end

  # POST /prompts
  # POST /prompts.json
  def create
    @prompt = Prompt.new(prompt_params)

    respond_to do |format|
      if @prompt.save
        format.html { redirect_to @prompt, notice: 'Prompt was successfully created.' }
        format.json { render :show, status: :created, location: @prompt }
      else
        format.html { render :new }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prompts/1
  # PATCH/PUT /prompts/1.json
  def update
    respond_to do |format|
      if @prompt.update(prompt_params)
        format.html { redirect_to @prompt, notice: 'Prompt was successfully updated.' }
        format.json { render :show, status: :ok, location: @prompt }
      else
        format.html { render :edit }
        format.json { render json: @prompt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prompts/1
  # DELETE /prompts/1.json
  def destroy
    @prompt.destroy
    respond_to do |format|
      format.html { redirect_to prompts_url, notice: 'Prompt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prompt
      @prompt = Prompt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prompt_params
      params.require(:prompt).permit(:user_id, :prompt_text, :prompt_placeholder_text, :results_text, :people_around_text, :prompt_type, :active, choices_attributes:[:choice_text,:_destroy,:id])
    end
end

app/helpers/prompts_helper.rb
module PromptsHelper
end

app/views/prompts/_form.html.erb
<%= form_for(@prompt) do |f| %>
  <% if @prompt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prompt.errors.count, "error") %> prohibited this prompt from being saved:</h2>

      <ul>
      <% @prompt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prompt_text %><br>
    <%= f.text_field :prompt_text, class: 'form-control'  %>
  </div>
  <div class="field">
    <%= f.label :results_text %><br>
    <%= f.text_field :results_text, class: 'form-control'  %>
  </div>
  <div class="field">
    <%= f.label :people_around_text %><br>
    <%= f.text_field :people_around_text, class: 'form-control'  %>
  </div>  
  <div id="placeholder_text" class="field">
    <label>Placeholder text</label><br>
    <%= f.text_field :prompt_placeholder_text, class: 'form-control'  %>
  </div>
  <div class="field">
    <%= f.label :prompt_type %><br>
    <%= f.select :prompt_type, options_for_select([ "open_ended", "multiple_choice", "duel", "geo" ], "open_ended"), class: 'form-control'  %>
  </div>
  
  <br/>
  <div id="nested_fields">
  <%= f.add_nested_fields_link :choices, 'Add prompt choice', class: 'btn btn-primary', role: 'button' %>
  <br/>
  <br/>
  <%= f.nested_fields_for :choices do |ff| %>
    <div class="panel panel-default">
      <div class="panel-heading">Choice <%= ff.remove_nested_fields_link '<i class="fa fa-trash"></i>'.html_safe, class: 'text-danger', role: 'button' %></div>
      <div class="panel-body">
        
        <%= ff.text_field :choice_text, class: 'form-control' %>
      </div>
    </div>
  <% end %>
  </div> <!-- #nested_fields -->

  </div>
  <div class="panel-footer"><%= link_to 'Back', prompts_path, class: "btn btn-warning" %> <%= f.submit class: 'btn btn-success' %></div>
</div>
<% end %>

<% content_for :footer do %>
<script type="text/javascript">
  $('#prompt_prompt_type').change(function(){
    prompt_show()}
  );
  
  $(document).ready(function() {
    prompt_show();
  });
  
  function prompt_show(){
    if ( $('#prompt_prompt_type option:selected').val() == "open_ended" ) {
      $("#nested_fields").hide();
      $('#placeholder_text').show();
    } else {
      $("#nested_fields").show();
      $('#placeholder_text').hide();
    }
  };
</script>

<% end %>

app/views/prompts/edit.html.erb
<br/>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Edit Prompt</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>

app/views/prompts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prompts <%= link_to '<i class="fa fa-plus-square"></i> Create Prompt'.html_safe, new_prompt_path, class: 'btn btn-primary' %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Prompt Text</th>
      <th>Responses</th>
      <th>Prompt type</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prompts.each do |prompt| %>
      <tr>
        <td><%= prompt.prompt_text %></td>
        <td><span class="badge"><%= prompt.answers.count %></span></td>
        <td><span class="label label-<%=prompt_type_label(prompt.prompt_type)%>"><%= prompt.prompt_type %></span></td>
        <td><input type="radio" name="is_active" id="is_active_<%=prompt.id%>" value="<%=prompt.id%>" <%=prompt.active? ? "checked":""%>></td>
        <td><%= link_to 'Show', prompt %></td>
        <td><%= link_to 'Edit', edit_prompt_path(prompt) %></td>
        <td><%= link_to 'Destroy', prompt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% content_for :footer do %>
<script type="text/javascript">
  $("input[name='is_active']:radio").change(function(){
    console.log($(this).val());
        $.ajax({
            url: "/prompts/set_active/"+$(this).val()
            });
  });
</script>
<% end %>

app/views/prompts/new.html.erb
<br/>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Create New Prompt</h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>

app/views/prompts/show.html.erb
<p id="notice"><%= notice %></p>
<br/>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Edit Prompt</h3>
  </div>
  <div class="panel-body">
<p>
  <strong>Text:</strong>
  <%= @prompt.prompt_text %>
</p>

<p>
  <strong>Prompt type:</strong>
  <%= @prompt.prompt_type %>
</p>

<p>
  <strong>Active:</strong>
  <%= @prompt.active %>
</p>
  </div>
  <div class="panel-footer">
    <%= link_to 'Edit', edit_prompt_path(@prompt), class: "btn btn-info" %>
    <%= link_to 'Back', prompts_path, class: "btn btn-warning" %>
    </div>
</div>