config/routes.rb
Rails.application.routes.draw do
  
  match 'answers/record' => 'answers#record', via: [:get, :post]
  match 'pages/word_cloud/:id' => 'pages#word_cloud', via: [:get]
  match 'pages/bar_chart/:id' => 'pages#bar_chart', via: [:get]
  match 'pages/geo_results/:id' => 'pages#geo_results', via: [:get]
  match 'pages/says_who/:id' => 'pages#says_who', via: [:get]
  match 'prompts/set_active/:id' => 'prompts#set_active', via: [:get, :post]
  
  resources :answers
  resources :choices
  resources :prompts, :has_many => :choices
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users
  
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
  
<% unless user_signed_in? %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Create Prompts', prompts_path %></li>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Edit account', edit_user_registration_path %></li>
        <li class="pull-right"><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Read the Room" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Read the Room" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <link href="/favicon.ico" rel="icon" type="image/x-icon" />
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= yield :footer %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Read the Room" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Read the Room" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Lato|Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <link href="/favicon.ico" rel="icon" type="image/x-icon" />
    <style type="text/css">
      .navbar-inner {
          min-height: 0px;
      }
      
      .navbar-brand,
      .navbar-nav li a {
          line-height: 66px;
          height: 66px;
          padding-top: 0;
          margin-top: 5px;
      }
      .navbar-custom { background-color: #0DACDD; }
      .btn-orange { background: #FB923A; }
    </style>
    <%= yield :head %>
  </head>
  <body style="background-color: #fdfdfd;">
    <header>
      <nav class="navbar navbar-custom navbar-fixed-top"  height="66">
        <div class="container">
          <div class="navbar-header">
            <%= image_tag "philz_coffee_logo.png", class: "navbar-brand", height: "66" %>
          </div>
          <ul class="nav navbar-nav"><%=yield :navbar_message %></ul>
          
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cog"></i><span class="caret"></span></a>
              <ul class="dropdown-menu">          
                <% if user_signed_in? %>
                  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
                <% else %>
                  <li><%= link_to 'Sign in', new_user_session_path %></li>
                  <li><%= link_to 'Sign up', new_user_registration_path %></li>
                <% end %>
              </ul> 
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <main role="main" style="padding-top: 40px;">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <%= yield :footer %>
  </body>
</html>